# Formula 1 WDC Prediction 2026

## Notebook 01 - Data Collection

**Author:** Regina Syahda Nabila Putri

**Date:** 2026-08-02

### Objective
Collect official Formula 1 race data for the 2026 season using FastF1.

## Workflow

1. Import required libraries
2. Enable FastF1 cache
3. Load Formula 1 session
4. Retrieve race results
5. Save raw dataset

In [1]:
import fastf1
import pandas as pd
print("✅ Libraries imported successfully!")

✅ Libraries imported successfully!

# Step 1: Import Libraries

## 🇬🇧 English

**Objective**

Import the required Python libraries for Formula 1 data collection.

---

## 🇮🇩 Bahasa Indonesia

**Tujuan**

Mengimpor library Python yang dibutuhkan untuk mengambil data Formula 1.

# Step 2: Configure FastF1 Cache

## 🎯 Objective

Configure a local cache directory to store downloaded Formula 1 data. This helps avoid downloading the same data repeatedly, making future executions much faster.

---

## 🇬🇧 English

### Purpose

FastF1 downloads data from external sources. By enabling a cache, downloaded files are stored locally so they can be reused in future sessions.

### Expected Output

A cache folder is successfully created and FastF1 is configured to use it.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Mengatur folder cache agar data Formula 1 yang sudah diunduh disimpan di komputer. Dengan begitu, saat notebook dijalankan kembali, data tidak perlu diunduh ulang sehingga proses menjadi lebih cepat.

### Output yang Diharapkan

Folder cache berhasil dibuat dan FastF1 siap menggunakan folder tersebut untuk menyimpan data.

In [2]:
from pathlib import Path

# Create cache folder
cache_path = Path("../data/cache")
cache_path.mkdir(parents=True, exist_ok=True)

# Enable FastF1 cache
fastf1.Cache.enable_cache(str(cache_path))

print(f"✅ Cache directory: {cache_path.resolve()}")
print("✅ FastF1 cache enabled successfully!")

✅ Cache directory: C:\Users\firdhan\Desktop\INTERN BISMILLAH\portofolio\Analisis F1 WDC 2026\data\cache
✅ FastF1 cache enabled successfully!

## 📊 Interpretation

### 🇬🇧 English

The cache directory has been successfully configured. Future requests for the same Formula 1 data will be loaded from the local cache instead of downloading them again.

---

### 🇮🇩 Bahasa Indonesia

Folder cache berhasil dibuat. Ketika data Formula 1 yang sama dibutuhkan lagi, FastF1 akan mengambilnya dari folder cache sehingga proses menjadi lebih cepat dan efisien.

# Step 3: Load Formula 1 Session

## 🎯 Objective

Load an official Formula 1 race session from the 2026 season using FastF1.

---

## 🇬🇧 English

### Purpose

A Formula 1 season consists of multiple Grand Prix weekends, and each weekend contains several sessions such as Practice, Qualifying, Sprint, and Race. In this project, we start by loading one race session to understand the structure of the official Formula 1 data before collecting the entire season.

### Expected Output

The selected Formula 1 race session is successfully loaded into the notebook and ready for further analysis.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Musim Formula 1 terdiri dari beberapa Grand Prix, dan setiap Grand Prix memiliki beberapa sesi seperti Practice, Qualifying, Sprint, dan Race. Pada tahap ini, kita akan memuat satu sesi balapan terlebih dahulu untuk memahami struktur data resmi Formula 1 sebelum mengambil seluruh data musim 2026.

### Output yang Diharapkan

Sesi balapan Formula 1 berhasil dimuat ke dalam notebook dan siap digunakan pada tahap analisis berikutnya.

In [3]:
# Load the 2026 Australian Grand Prix Race session
session = fastf1.get_session(
    2026,
    "Australia",
    "R"
)

# Download and load the session data
session.load()

print("✅ Formula 1 session loaded successfully!")

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

✅ Formula 1 session loaded successfully!

## 📊 Interpretation

### 🇬🇧 English

The Formula 1 race session has been successfully loaded into the notebook. At this stage, the `session` object contains official race information that can be accessed for further analysis, such as race results, lap times, weather conditions, and telemetry data.

---

### 🇮🇩 Bahasa Indonesia

Sesi balapan Formula 1 berhasil dimuat ke dalam notebook. Pada tahap ini, objek `session` telah berisi berbagai informasi resmi Formula 1 yang dapat digunakan untuk analisis selanjutnya, seperti hasil balapan, data lap, kondisi cuaca, dan telemetry.

# Step 4: Explore Race Results

## 🎯 Objective

Retrieve the official race results from the loaded Formula 1 session and explore the dataset structure.

---

## 🇬🇧 English

### Purpose

The race results dataset contains the official finishing information for every driver in the selected Grand Prix. Before performing any analysis, it is important to understand the available columns and data structure.

### Expected Output

The first few rows of the race results dataset are displayed successfully.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Mengambil data hasil balapan resmi dari sesi Formula 1 yang telah dimuat sebelumnya dan memahami struktur dataset yang tersedia.

### Output yang Diharapkan

Lima baris pertama dari dataset hasil balapan berhasil ditampilkan.

In [4]:
# Retrieve official race results
results = session.results

# Display the first five rows
results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:23:06.801000,Finished,25.0,58.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:02.974000,Finished,18.0,58.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:15.519000,Finished,15.0,58.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,7.0,NaT,NaT,NaT,0 days 00:00:16.144000,Finished,12.0,58.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:51.741000,Finished,10.0,58.0

# Step 5: Understand the Dataset

## 🎯 Objective

Understand the structure of the race results dataset by examining its columns, data types, and dimensions before performing any analysis.

---

## 🇬🇧 English

### Purpose

Before cleaning or analyzing a dataset, it is important to understand what information is available. This step helps identify the available variables and their data types.

### Expected Output

A complete overview of the dataset structure, including column names, data types, and dataset dimensions.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Memahami struktur dataset hasil balapan sebelum melakukan proses pembersihan data maupun analisis.

### Output yang Diharapkan

Menampilkan daftar kolom, tipe data setiap kolom, serta ukuran dataset.

In [5]:
results.shape

(22, 22)

In [6]:
results.columns

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps'],
      dtype='object')

In [7]:
results.dtypes

DriverNumber                   object
BroadcastName                  object
Abbreviation                   object
DriverId                       object
TeamName                       object
TeamColor                      object
TeamId                         object
FirstName                      object
LastName                       object
FullName                       object
HeadshotUrl                    object
CountryCode                    object
Position                      float64
ClassifiedPosition             object
GridPosition                  float64
Q1                    timedelta64[ns]
Q2                    timedelta64[ns]
Q3                    timedelta64[ns]
Time                  timedelta64[ns]
Status                         object
Points                        float64
Laps                          float64
dtype: object

In [8]:
results.info()

<class 'fastf1.core.SessionResults'>
Index: 22 entries, 63 to 27
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        22 non-null     object
 1   BroadcastName       22 non-null     object
 2   Abbreviation        22 non-null     object
 3   DriverId            22 non-null     object
 4   TeamName            22 non-null     object
 5   TeamColor           22 non-null     object
 6   TeamId              22 non-null     object
 7   FirstName           22 non-null     object
 8   LastName            22 non-null     object
 9   FullName            22 non-null     object
 10  HeadshotUrl         22 non-null     object
 11  CountryCode         22 non-null     object
 12  Position            22 non-null     float64
 13  ClassifiedPosition  22 non-null     object
 14  GridPosition        22 non-null     float64
 15  Q1                  0 non-null      timedelta64[ns]
 16  Q2                  0 non-null      timedelta64[ns]
 17  Q3                  0 non-null      timedelta64[ns]
 18  Time                16 non-null     timedelta64[ns]
 19  Status              22 non-null     object
 20  Points              22 non-null     float64
 21  Laps                22 non-null     float64
dtypes: float64(4), object(14), timedelta64[ns](4)
memory usage: 4.5+ KB

In [9]:
results.info()

<class 'fastf1.core.SessionResults'>
Index: 22 entries, 63 to 27
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        22 non-null     object
 1   BroadcastName       22 non-null     object
 2   Abbreviation        22 non-null     object
 3   DriverId            22 non-null     object
 4   TeamName            22 non-null     object
 5   TeamColor           22 non-null     object
 6   TeamId              22 non-null     object
 7   FirstName           22 non-null     object
 8   LastName            22 non-null     object
 9   FullName            22 non-null     object
 10  HeadshotUrl         22 non-null     object
 11  CountryCode         22 non-null     object
 12  Position            22 non-null     float64
 13  ClassifiedPosition  22 non-null     object
 14  GridPosition        22 non-null     float64
 15  Q1                  0 non-null      timedelta64[ns]
 16  Q2                  0 non-null      timedelta64[ns]
 17  Q3                  0 non-null      timedelta64[ns]
 18  Time                16 non-null     timedelta64[ns]
 19  Status              22 non-null     object
 20  Points              22 non-null     float64
 21  Laps                22 non-null     float64
dtypes: float64(4), object(14), timedelta64[ns](4)
memory usage: 4.5+ KB

# Step 6: Identify Missing Values

## 🎯 Objective

Check whether the dataset contains missing values before proceeding to data cleaning.

---

## 🇬🇧 English

### Purpose

Missing values may affect data analysis and prediction performance. Identifying them early helps determine the appropriate cleaning strategy.

### Expected Output

A summary showing the number of missing values in each column.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Memeriksa apakah terdapat data yang kosong (missing values) pada dataset sebelum dilakukan proses pembersihan data.

### Output yang Diharapkan

Menampilkan jumlah missing value pada setiap kolom.

In [10]:
results.isnull().sum()

DriverNumber           0
BroadcastName          0
Abbreviation           0
DriverId               0
TeamName               0
TeamColor              0
TeamId                 0
FirstName              0
LastName               0
FullName               0
HeadshotUrl            0
CountryCode            0
Position               0
ClassifiedPosition     0
GridPosition           0
Q1                    22
Q2                    22
Q3                    22
Time                   6
Status                 0
Points                 0
Laps                   0
dtype: int64

In [11]:
missing = results.isnull().sum().sort_values(ascending=False)

missing

Q3                    22
Q2                    22
Q1                    22
Time                   6
DriverNumber           0
BroadcastName          0
TeamColor              0
TeamName               0
DriverId               0
Abbreviation           0
TeamId                 0
FirstName              0
LastName               0
FullName               0
ClassifiedPosition     0
Position               0
CountryCode            0
HeadshotUrl            0
GridPosition           0
Status                 0
Points                 0
Laps                   0
dtype: int64

## 📊 Interpretation

### 🇬🇧 English

The missing value analysis shows that not all columns contain complete data. Some variables, such as **Q1**, **Q2**, and **Q3**, have missing values because this dataset represents the **Race** session rather than the **Qualifying** session.

This result indicates that not every missing value is an error. Some missing values are expected based on the context of the dataset. Understanding the reason behind missing values is an important step before deciding whether to remove, keep, or transform them during data cleaning.

---

### 🇮🇩 Bahasa Indonesia

Hasil pemeriksaan missing value menunjukkan bahwa tidak semua kolom memiliki data lengkap. Beberapa variabel seperti **Q1**, **Q2**, dan **Q3** kosong karena dataset yang digunakan berasal dari sesi **Race**, bukan sesi **Qualifying**.

Hal ini menunjukkan bahwa tidak semua missing value merupakan kesalahan data. Beberapa memang wajar terjadi sesuai dengan konteks dataset. Oleh karena itu, sebelum melakukan data cleaning, kita harus memahami penyebab missing value agar dapat menentukan penanganan yang tepat.

# Step 7: Select Relevant Features

## 🎯 Objective

Identify and select the most relevant variables for predicting the 2026 Formula 1 World Drivers' Championship (WDC).

---

## 🇬🇧 English

### Purpose

The original dataset contains many variables, but not all of them are useful for this project. Selecting only the relevant features simplifies the analysis and improves data quality for future prediction models.

### Expected Output

A new dataset containing only the selected features required for WDC analysis.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Dataset asli memiliki banyak kolom, tetapi tidak semuanya dibutuhkan dalam proyek ini. Dengan memilih fitur yang relevan, proses analisis menjadi lebih sederhana dan lebih fokus pada faktor-faktor yang memengaruhi hasil kejuaraan dunia.

### Output yang Diharapkan

Terbentuk dataset baru yang hanya berisi kolom-kolom penting untuk analisis dan prediksi WDC.

In [12]:
# Select relevant columns for WDC analysis
selected_columns = [
    "DriverNumber",
    "FullName",
    "TeamName",
    "Position",
    "GridPosition",
    "Status",
    "Points",
    "Laps",
    "Time"
]

race_results = results[selected_columns]

race_results.head()

,DriverNumber,FullName,TeamName,Position,GridPosition,Status,Points,Laps,Time
63,63,George Russell,Mercedes,1.0,1.0,Finished,25.0,58.0,0 days 01:23:06.801000
12,12,Kimi Antonelli,Mercedes,2.0,2.0,Finished,18.0,58.0,0 days 00:00:02.974000
16,16,Charles Leclerc,Ferrari,3.0,4.0,Finished,15.0,58.0,0 days 00:00:15.519000
44,44,Lewis Hamilton,Ferrari,4.0,7.0,Finished,12.0,58.0,0 days 00:00:16.144000
1,1,Lando Norris,McLaren,5.0,6.0,Finished,10.0,58.0,0 days 00:00:51.741000

## 📊 Interpretation

### 🇬🇧 English

A new dataset has been created containing only the variables relevant to this project. Removing unnecessary columns makes the dataset easier to understand, reduces complexity, and prepares it for further analysis and prediction.

---

### 🇮🇩 Bahasa Indonesia

Dataset baru berhasil dibuat dengan hanya menyimpan kolom-kolom yang relevan untuk proyek ini. Menghapus kolom yang tidak diperlukan membuat proses analisis menjadi lebih sederhana, lebih terfokus, dan mempersiapkan data untuk tahap berikutnya seperti eksplorasi data dan prediksi.

# Step 8: Export Processed Dataset

## 🎯 Objective

Save the selected race results into a CSV file for future analysis.

---

## 🇬🇧 English

### Purpose

Exporting the processed dataset ensures that the cleaned and selected data can be reused without repeating the entire data collection process.

### Expected Output

A CSV file containing the selected race result variables is successfully saved in the `data/raw` directory.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Menyimpan dataset hasil seleksi kolom ke dalam file CSV agar dapat digunakan kembali pada tahap analisis berikutnya tanpa harus mengambil data dari FastF1 lagi.

### Output yang Diharapkan

File CSV berhasil tersimpan di folder `data/raw`.

In [13]:
# Export race results to CSV

output_file = Path("../data/raw/australian_gp_2026_results.csv")

race_results.to_csv(output_file, index=False)

print(f"Dataset successfully saved to:\n{output_file}")

Dataset successfully saved to:
..\data\raw\australian_gp_2026_results.csv

In [14]:
# Export race results to CSV

output_file = Path("../data/raw/australian_gp_2026_results.csv")

race_results.to_csv(output_file, index=False)

print(f"Dataset successfully saved to:\n{output_file}")

Dataset successfully saved to:
..\data\raw\australian_gp_2026_results.csv