# Formula 1 World Drivers' Championship (WDC) Prediction 2026

## Notebook 02 - Collect All Race Results

**Author:** Regina Syahda Nabila Putri

**Project:** Predicting the 2026 Formula 1 World Drivers' Championship using official race data from FastF1.

---

## 🎯 Objective

Automatically collect official race results from every completed Formula 1 Grand Prix in the 2026 season and combine them into a single dataset for further analysis and prediction.

---

## 📌 Workflow

1. Import required libraries
2. Configure FastF1 cache
3. Define completed Grands Prix
4. Create a data collection function
5. Collect race results
6. Combine all race results
7. Export the master dataset

# Step 1: Import Libraries

## 🎯 Objective

Import all Python libraries required for collecting and processing Formula 1 race data.

---

## 🇬🇧 English

### Purpose

Import the required libraries for data collection, manipulation, and file management.

### Expected Output

All required libraries are successfully imported.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Mengimpor seluruh library Python yang diperlukan untuk mengambil, mengolah, dan menyimpan data Formula 1.

### Output yang Diharapkan

Seluruh library berhasil diimpor tanpa error.

In [27]:
import fastf1
import pandas as pd

from pathlib import Path

## 📊 Interpretation

### 🇬🇧 English

The required Python libraries have been successfully imported. The notebook is now ready to collect and process Formula 1 race data.

---

### 🇮🇩 Bahasa Indonesia

Library Python yang dibutuhkan berhasil diimpor. Notebook sekarang siap digunakan untuk mengambil dan mengolah data Formula 1.

# Step 2: Configure FastF1 Cache

## 🎯 Objective

Configure a local cache directory to store downloaded Formula 1 data.

---

## 🇬🇧 English

### Purpose

Caching improves performance by storing downloaded data locally, reducing the need to download the same data repeatedly.

### Expected Output

FastF1 cache is successfully enabled.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Mengatur folder cache agar data Formula 1 yang telah diunduh dapat digunakan kembali tanpa perlu mengunduh ulang.

### Output yang Diharapkan

FastF1 berhasil menggunakan folder cache lokal.

In [28]:
cache_path = Path("../data/cache")

cache_path.mkdir(parents=True, exist_ok=True)

fastf1.Cache.enable_cache(str(cache_path))

print("✅ Cache enabled successfully!")

✅ Cache enabled successfully!

## 📊 Interpretation

### 🇬🇧 English

The cache directory has been configured successfully. Future requests for the same data will be loaded from the local cache, reducing download time.

---

### 🇮🇩 Bahasa Indonesia

Folder cache berhasil dikonfigurasi. Pengambilan data berikutnya akan lebih cepat karena FastF1 menggunakan data yang sudah tersimpan secara lokal.

# Step 3: Define Completed Grands Prix

## 🎯 Objective

Create a list of all completed Formula 1 Grands Prix in the 2026 season that will be collected automatically.

---

## 🇬🇧 English

### Purpose

Instead of manually writing the same code for every race, we first define all completed Grands Prix in a Python list. This approach makes the data collection process scalable and easier to maintain.

### Expected Output

A Python list containing the names of all completed Grands Prix.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Daripada menulis kode yang sama berulang kali untuk setiap balapan, kita terlebih dahulu membuat daftar seluruh Grand Prix yang telah selesai dalam bentuk Python list. Cara ini membuat proses pengambilan data menjadi lebih otomatis dan mudah dikembangkan.

### Output yang Diharapkan

Sebuah Python list yang berisi nama-nama Grand Prix yang telah selesai.

In [29]:
# List of completed Formula 1 Grands Prix in the 2026 season

completed_grands_prix = [
    "Australia",
    "China",
    "Japan",
    "Miami",
    "Canada",
    "Monaco",
    "Austria",
    "Great Britain",
    "Belgium",
    "Hungary",
    "Netherlands",
]

print("Completed Grands Prix:")
print(completed_grands_prix)

print(f"\nTotal completed races: {len(completed_grands_prix)}")

Completed Grands Prix:
['Australia', 'China', 'Japan', 'Miami', 'Canada', 'Monaco', 'Austria', 'Great Britain', 'Belgium', 'Hungary', 'Netherlands']

Total completed races: 11

## 📊 Interpretation

### 🇬🇧 English

A list of completed Grands Prix has been created successfully. This list will be used as the input for the automated data collection process in the following steps.

---

### 🇮🇩 Bahasa Indonesia

Daftar Grand Prix yang telah selesai berhasil dibuat. Daftar ini akan digunakan sebagai input untuk proses pengambilan data secara otomatis pada langkah berikutnya.

# Step 4: Create a Data Collection Function

## 🎯 Objective

Create a reusable Python function to automatically collect race results for any completed Formula 1 Grand Prix.

---

## 🇬🇧 English

### Purpose

Instead of writing the same code for every Grand Prix, we create a reusable function. This improves code readability, reduces duplication, and makes the data collection process scalable.

### Expected Output

A Python function that accepts a Grand Prix name as input and returns the corresponding race results as a DataFrame.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Membuat sebuah fungsi Python yang dapat digunakan kembali untuk mengambil hasil balapan dari Grand Prix mana pun. Dengan cara ini, kita tidak perlu menulis kode yang sama berulang kali.

### Output yang Diharapkan

Sebuah fungsi Python yang menerima nama Grand Prix sebagai input dan mengembalikan hasil balapan dalam bentuk DataFrame.

In [30]:
def collect_race_results(grand_prix):
    """
    Collect official Formula 1 race results for a given Grand Prix.
    """

    print(f"📥 Collecting data for {grand_prix} Grand Prix...")

    # Explicit mapping between our dataset names and FastF1 event names
    race_mapping = {
        "Australia": "Australian Grand Prix",
        "China": "Chinese Grand Prix",
        "Japan": "Japanese Grand Prix",
        "Miami": "Miami Grand Prix",
        "Canada": "Canadian Grand Prix",
        "Monaco": "Monaco Grand Prix",
        "Austria": "Austrian Grand Prix",
        "Great Britain": "British Grand Prix",
        "Belgium": "Belgian Grand Prix",
        "Hungary": "Hungarian Grand Prix",
        "Netherlands": "Dutch Grand Prix",
    }

    event_name = race_mapping.get(grand_prix, grand_prix)

    # Load race session
    session = fastf1.get_session(
        2026,
        event_name,
        "R"
    )

    session.load()

    # Retrieve race results
    results = session.results.copy()

    # Stop if no results are available
    if results.empty:
        raise ValueError(
            f"❌ No race results found for {grand_prix}."
        )

    # Add our standardized Grand Prix name
    results["GrandPrix"] = grand_prix

    print(
        f"✅ {grand_prix}: "
        f"{len(results)} drivers collected."
    )

    return results

## 📊 Interpretation

### 🇬🇧 English

A reusable function has been successfully created. Instead of writing the same code repeatedly for every Grand Prix, the function can now collect race results by simply providing the Grand Prix name.

---

### 🇮🇩 Bahasa Indonesia

Sebuah fungsi yang dapat digunakan kembali berhasil dibuat. Dengan fungsi ini, kita tidak perlu lagi menulis kode yang sama untuk setiap Grand Prix. Cukup memberikan nama Grand Prix sebagai input, maka data hasil balapan akan diambil secara otomatis.

# Step 5: Test the Data Collection Function

## 🎯 Objective

Test the data collection function using a single completed Grand Prix to ensure it works correctly before collecting the entire season.

---

## 🇬🇧 English

### Purpose

Before automating the data collection process, it is important to verify that the function returns the expected race results for one Grand Prix.

### Expected Output

The function successfully returns the official race results for the selected Grand Prix.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Sebelum mengotomatisasi pengambilan seluruh Grand Prix, kita perlu memastikan bahwa fungsi yang telah dibuat dapat bekerja dengan benar pada satu Grand Prix terlebih dahulu.

### Output yang Diharapkan

Fungsi berhasil mengembalikan data hasil balapan resmi dari Grand Prix yang dipilih.

In [31]:
# Test the function using the Australian Grand Prix

australia_results = collect_race_results("Australia")

australia_results.head()

📥 Collecting data for Australia Grand Prix...

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

✅ Australia: 22 drivers collected.

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,GrandPrix
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1,1.0,NaT,NaT,NaT,0 days 01:23:06.801000,Finished,25.0,58.0,Australia
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2,2.0,NaT,NaT,NaT,0 days 00:00:02.974000,Finished,18.0,58.0,Australia
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3,4.0,NaT,NaT,NaT,0 days 00:00:15.519000,Finished,15.0,58.0,Australia
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4,7.0,NaT,NaT,NaT,0 days 00:00:16.144000,Finished,12.0,58.0,Australia
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5,6.0,NaT,NaT,NaT,0 days 00:00:51.741000,Finished,10.0,58.0,Australia

## 📊 Interpretation

### 🇬🇧 English

The data collection function successfully retrieved the official race results for the Australian Grand Prix. The session data was loaded from the local cache, making the process faster. This confirms that the function is working correctly and is ready to be applied to multiple Grands Prix.

---

### 🇮🇩 Bahasa Indonesia

Fungsi berhasil mengambil data hasil balapan resmi Australian Grand Prix. Data dimuat dari cache lokal sehingga proses menjadi lebih cepat. Hal ini menunjukkan bahwa fungsi bekerja dengan baik dan siap digunakan untuk mengambil data dari beberapa Grand Prix secara otomatis.

# Step 6: Collect All Completed Grand Prix Results

## 🎯 Objective

Automatically collect race results from all completed Formula 1 Grands Prix using a loop.

---

## 🇬🇧 English

### Purpose

Instead of collecting race results manually one by one, we use a loop to automate the process for every completed Grand Prix.

### Expected Output

A combined dataset containing race results from all completed Grands Prix.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Mengotomatisasi proses pengambilan data seluruh Grand Prix yang telah selesai menggunakan perulangan (`for` loop).

### Output yang Diharapkan

Sebuah dataset gabungan yang berisi hasil balapan dari seluruh Grand Prix yang telah selesai.

In [32]:
# Create an empty list to store race results
all_results = []

# Collect data for each completed Grand Prix
for grand_prix in completed_grands_prix:

    race = collect_race_results(grand_prix)

    all_results.append(race)

print(f"\n✅ Successfully collected {len(all_results)} races.")

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

📥 Collecting data for Australia Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ Australia: 22 drivers collected.
📥 Collecting data for China Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 1)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 5)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
core        WARNING 	Driver 12 completed the race distance 00:00.022000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '87', '10', '30', '6', '55', '43', '27', '41', '77', '31', '11', '3', '14', '18', '81', '1', '5', '23']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ China: 22 drivers collected.
📥 Collecting data for Japan Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '81', '16', '63', '1', '44', '10', '3', '30', '31', '27', '6', '5', '41', '55', '43', '11', '14', '77', '23', '18', '87']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ Japan: 22 drivers collected.
📥 Collecting data for Miami Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 12 completed the race distance 00:00.027000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '1', '81', '63', '3', '44', '43', '16', '55', '23', '87', '5', '31', '41', '14', '11', '18', '77', '27', '30', '10', '6']

✅ Miami: 22 drivers collected.
📥 Collecting data for Canada Grand Prix...

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 41)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '3', '16', '6', '43', '30', '10', '55', '87', '81', '27', '5', '31', '18', '77', '11', '1', '63', '14', '23', '41']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ Canada: 22 drivers collected.
📥 Collecting data for Monaco Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ Monaco: 22 drivers collected.
📥 Collecting data for Austria Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 63 completed the race distance 00:00.530000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '3', '12', '81', '44', '6', '1', '16', '30', '41', '5', '27', '10', '87', '43', '31', '23', '14', '18', '55', '11', '77']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

✅ Austria: 22 drivers collected.
📥 Collecting data for Great Britain Grand Prix...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['16', '63', '44', '1', '6', '30', '41', '5', '43', '10', '81', '87', '31', '11', '12', '77', '55', '14', '18', '3', '23', '27']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ Great Britain: 22 drivers collected.
📥 Collecting data for Belgium Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Driver 12 completed the race distance 00:00.045000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '16', '3', '44', '81', '6', '1', '5', '41', '43', '10', '30', '27', '87', '23', '55', '31', '77', '14', '18', '11', '63']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ Belgium: 22 drivers collected.
📥 Collecting data for Hungary Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '12', '16', '44', '6', '63', '30', '27', '41', '5', '10', '18', '14', '43', '31', '23', '55', '87', '81', '11', '77']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✅ Hungary: 22 drivers collected.
📥 Collecting data for Netherlands Grand Prix...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 41: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 1 completed the race distance 00:01.577000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '12', '63', '44', '16', '81', '30', '27', '14', '10', '22', '41', '5', '43', '11', '55', '23', '77', '31', '18', '87', '3']

✅ Netherlands: 22 drivers collected.

✅ Successfully collected 11 races.

## 📊 Interpretation

### 🇬🇧 English

The automated data collection process completed successfully. Race results from all completed Formula 1 Grands Prix were retrieved and stored in a Python list named `all_results`.

At this stage, each element in the list is a separate DataFrame representing one Grand Prix. These DataFrames will be combined into a single master dataset in the next step.

---

### 🇮🇩 Bahasa Indonesia

Proses pengambilan data secara otomatis berhasil diselesaikan. Hasil balapan dari seluruh Grand Prix Formula 1 yang telah selesai berhasil diambil dan disimpan ke dalam sebuah list Python bernama `all_results`.

Pada tahap ini, setiap elemen di dalam list merupakan sebuah DataFrame yang mewakili satu Grand Prix. Seluruh DataFrame tersebut akan digabungkan menjadi satu dataset utama pada langkah berikutnya.

# Step 7: Combine All Race Results

## 🎯 Objective

Combine all collected race result DataFrames into a single master dataset.

---

## 🇬🇧 English

### Purpose

After collecting race results from multiple Grand Prix events, the individual DataFrames need to be merged into a single dataset. This master dataset will be used for data cleaning, exploratory data analysis (EDA), visualization, and prediction.

### Expected Output

A single DataFrame containing race results from all completed Formula 1 Grands Prix.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Menggabungkan seluruh DataFrame hasil balapan menjadi satu dataset utama yang akan digunakan pada tahap data cleaning, EDA, visualisasi, dan prediksi.

### Output yang Diharapkan

Satu DataFrame yang berisi seluruh hasil balapan Formula 1 yang telah selesai.

In [33]:
# Combine all race results into one DataFrame

wdc_results = pd.concat(
    all_results,
    ignore_index=True
)

print("Dataset combined successfully!")

wdc_results.head()

Dataset combined successfully!

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,GrandPrix
0,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1,1.0,NaT,NaT,NaT,0 days 01:23:06.801000,Finished,25.0,58.0,Australia
1,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2,2.0,NaT,NaT,NaT,0 days 00:00:02.974000,Finished,18.0,58.0,Australia
2,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3,4.0,NaT,NaT,NaT,0 days 00:00:15.519000,Finished,15.0,58.0,Australia
3,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4,7.0,NaT,NaT,NaT,0 days 00:00:16.144000,Finished,12.0,58.0,Australia
4,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5,6.0,NaT,NaT,NaT,0 days 00:00:51.741000,Finished,10.0,58.0,Australia

## 📊 Interpretation

### 🇬🇧 English

The individual race result datasets have been successfully combined into one master dataset. Each row now represents a driver's result from a specific Grand Prix, making the dataset ready for further analysis.

---

### 🇮🇩 Bahasa Indonesia

Seluruh dataset hasil balapan berhasil digabungkan menjadi satu dataset utama. Setiap baris merepresentasikan hasil seorang pembalap pada satu Grand Prix sehingga dataset siap digunakan untuk analisis berikutnya.

# Step 8: Inspect the Master Dataset

## 🎯 Objective

Verify the structure and quality of the combined dataset.

---

## 🇬🇧 English

### Purpose

Inspect the dimensions and structure of the combined dataset before exporting it.

### Expected Output

The dataset dimensions, column information, and sample rows are displayed.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Memastikan struktur dan kualitas dataset gabungan sebelum disimpan.

### Output yang Diharapkan

Menampilkan ukuran dataset, informasi kolom, dan beberapa baris pertama dataset.

In [34]:
print("Dataset Shape:")
print(wdc_results.shape)

print("\n")

wdc_results.info()

Dataset Shape:
(242, 23)


<class 'fastf1.core.SessionResults'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        242 non-null    object
 1   BroadcastName       242 non-null    object
 2   Abbreviation        242 non-null    object
 3   DriverId            242 non-null    object
 4   TeamName            242 non-null    object
 5   TeamColor           242 non-null    object
 6   TeamId              242 non-null    object
 7   FirstName           242 non-null    object
 8   LastName            242 non-null    object
 9   FullName            242 non-null    object
 10  HeadshotUrl         242 non-null    object
 11  CountryCode         242 non-null    object
 12  Position            242 non-null    float64
 13  ClassifiedPosition  242 non-null    object
 14  GridPosition        242 non-null    float64
 15  Q1                  0 non-null      timedelta64[ns]
 16  Q2                  0 non-null      timedelta64[ns]
 17  Q3                  0 non-null      timedelta64[ns]
 18  Time                191 non-null    timedelta64[ns]
 19  Status              242 non-null    object
 20  Points              242 non-null    float64
 21  Laps                242 non-null    float64
 22  GrandPrix           242 non-null    object
dtypes: float64(4), object(15), timedelta64[ns](4)
memory usage: 43.6+ KB

In [35]:
# Preview the combined dataset

wdc_results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,GrandPrix
0,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1,1.0,NaT,NaT,NaT,0 days 01:23:06.801000,Finished,25.0,58.0,Australia
1,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2,2.0,NaT,NaT,NaT,0 days 00:00:02.974000,Finished,18.0,58.0,Australia
2,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3,4.0,NaT,NaT,NaT,0 days 00:00:15.519000,Finished,15.0,58.0,Australia
3,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4,7.0,NaT,NaT,NaT,0 days 00:00:16.144000,Finished,12.0,58.0,Australia
4,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5,6.0,NaT,NaT,NaT,0 days 00:00:51.741000,Finished,10.0,58.0,Australia

## 📊 Interpretation

### 🇬🇧 English

The master dataset has been successfully inspected. The dataset dimensions, column structure, and sample records confirm that race results from all completed Grands Prix have been combined correctly into a single DataFrame.

The dataset is complete and ready to be exported for the next stages of the project, including data cleaning, exploratory data analysis (EDA), visualization, and predictive modeling.

---

### 🇮🇩 Bahasa Indonesia

Dataset utama telah berhasil diperiksa. Ukuran dataset, struktur kolom, dan contoh data menunjukkan bahwa hasil balapan dari seluruh Grand Prix yang telah selesai berhasil digabungkan ke dalam satu DataFrame.

Dataset kini siap untuk diekspor dan digunakan pada tahap selanjutnya, yaitu data cleaning, exploratory data analysis (EDA), visualisasi, serta pembuatan model prediksi.

# Step 9: Export the Master Dataset

## 🎯 Objective

Export the combined Formula 1 race results into a CSV file for future analysis.

---

## 🇬🇧 English

### Purpose

Save the master dataset locally so it can be reused in future notebooks without downloading the race data again.

### Expected Output

A CSV file named **wdc_2026_results.csv** is successfully created inside the **data/raw** folder.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Menyimpan dataset utama ke dalam file CSV agar dapat digunakan kembali pada notebook berikutnya tanpa perlu mengunduh ulang data Formula 1.

### Output yang Diharapkan

Sebuah file CSV bernama **wdc_2026_results.csv** berhasil dibuat di dalam folder **data/raw**.

In [36]:
# Define output path
output_path = Path("../data/raw/wdc_2026_results.csv")

# Export the master dataset
wdc_results.to_csv(output_path, index=False)

print("✅ Master dataset exported successfully!")
print(f"Saved to: {output_path}")

✅ Master dataset exported successfully!
Saved to: ..\data\raw\wdc_2026_results.csv

## 📊 Interpretation

### 🇬🇧 English

The master dataset has been successfully exported as a CSV file. This file will serve as the primary data source for the remaining stages of the project, including data cleaning, exploratory data analysis (EDA), dashboard development, and World Drivers' Championship (WDC) prediction.

Exporting the dataset also improves reproducibility because future notebooks can directly load the CSV file without downloading the race data again.

---

### 🇮🇩 Bahasa Indonesia

Dataset utama berhasil diekspor ke dalam format CSV. File ini akan menjadi sumber data utama untuk tahap-tahap selanjutnya, seperti data cleaning, exploratory data analysis (EDA), pembuatan dashboard, dan prediksi World Drivers' Championship (WDC).

Menyimpan dataset dalam bentuk CSV juga meningkatkan reproducibility karena notebook berikutnya dapat langsung membaca file tersebut tanpa perlu mengunduh ulang data balapan.