# Formula 1 WDC Prediction 2026

## Notebook 03 - Data Cleaning

**Author:** Regina Syahda Nabila Putri

**Date:**

---

## 🎯 Objective

Clean and validate the Formula 1 race results dataset before performing exploratory data analysis (EDA), dashboard development, and predictive modeling.

## Workflow

1. Import Libraries
2. Load Master Dataset
3. Inspect Dataset
4. Check Data Types
5. Check Missing Values
6. Check Duplicate Records
7. Clean Dataset
8. Validate Clean Dataset
9. Export Clean Dataset
10. Summary

# Step 1: Import Libraries

## 🎯 Objective

Import the required libraries for data cleaning and validation.

---

## 🇬🇧 English

### Purpose

Load the Python libraries needed throughout this notebook.

### Expected Output

All required libraries are imported successfully.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Mengimpor library Python yang dibutuhkan selama proses data cleaning.

### Output yang Diharapkan

Seluruh library berhasil diimpor tanpa error.

In [98]:
import pandas as pd
from pathlib import Path

## 📊 Interpretation

### 🇬🇧 English

The required libraries have been successfully imported and are ready for the data cleaning process.

---

### 🇮🇩 Bahasa Indonesia

Library yang diperlukan telah berhasil diimpor dan siap digunakan untuk proses data cleaning.

# Step 2: Load the Master Dataset

## 🎯 Objective

Load the master dataset created in Notebook 02.

---

## 🇬🇧 English

### Purpose

Read the exported CSV file into a pandas DataFrame for further inspection and cleaning.

### Expected Output

The master dataset is successfully loaded into memory.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Memuat dataset utama hasil Notebook 02 ke dalam DataFrame pandas untuk proses pemeriksaan dan pembersihan data.

### Output yang Diharapkan

Dataset berhasil dimuat ke dalam DataFrame.

In [99]:
dataset_path = Path("../data/raw/wdc_2026_results.csv")

wdc = pd.read_csv(dataset_path)

print("✅ Dataset loaded successfully!")

wdc.head()

✅ Dataset loaded successfully!

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,GrandPrix
0,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1,1.0,NaN,NaN,NaN,0 days 01:23:06.801000,Finished,25.0,58.0,Australia
1,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2,2.0,NaN,NaN,NaN,0 days 00:00:02.974000,Finished,18.0,58.0,Australia
2,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3,4.0,NaN,NaN,NaN,0 days 00:00:15.519000,Finished,15.0,58.0,Australia
3,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4,7.0,NaN,NaN,NaN,0 days 00:00:16.144000,Finished,12.0,58.0,Australia
4,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5,6.0,NaN,NaN,NaN,0 days 00:00:51.741000,Finished,10.0,58.0,Australia

## 📊 Interpretation

### 🇬🇧 English

The master dataset has been successfully loaded into a pandas DataFrame. The dataset is now ready for inspection and data cleaning.

---

### 🇮🇩 Bahasa Indonesia

Dataset utama berhasil dimuat ke dalam DataFrame pandas. Dataset kini siap untuk diperiksa dan dibersihkan sebelum digunakan pada tahap analisis berikutnya.

# Step 3: Inspect the Dataset

## 🎯 Objective

Understand the overall structure of the dataset before performing data cleaning.

---

## 🇬🇧 English

### Purpose

Display the dataset dimensions, column information, and sample records to understand its structure.

### Expected Output

The dataset shape, column information, and preview are displayed successfully.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Menampilkan ukuran dataset, informasi kolom, dan beberapa baris pertama untuk memahami struktur data.

### Output yang Diharapkan

Ukuran dataset, informasi kolom, dan contoh data berhasil ditampilkan.

In [100]:
print("Dataset Shape:")
print(wdc.shape)

Dataset Shape:
(242, 23)

In [101]:
wdc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        242 non-null    int64
 1   BroadcastName       242 non-null    object
 2   Abbreviation        242 non-null    object
 3   DriverId            242 non-null    object
 4   TeamName            242 non-null    object
 5   TeamColor           242 non-null    object
 6   TeamId              242 non-null    object
 7   FirstName           242 non-null    object
 8   LastName            242 non-null    object
 9   FullName            242 non-null    object
 10  HeadshotUrl         241 non-null    object
 11  CountryCode         0 non-null      float64
 12  Position            242 non-null    float64
 13  ClassifiedPosition  242 non-null    object
 14  GridPosition        242 non-null    float64
 15  Q1                  0 non-null      float64
 16  Q2                  0 non-null      float64
 17  Q3                  0 non-null      float64
 18  Time                191 non-null    object
 19  Status              242 non-null    object
 20  Points              242 non-null    float64
 21  Laps                242 non-null    float64
 22  GrandPrix           242 non-null    object
dtypes: float64(8), int64(1), object(14)
memory usage: 43.6+ KB

In [102]:
wdc.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,GrandPrix
0,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1,1.0,NaN,NaN,NaN,0 days 01:23:06.801000,Finished,25.0,58.0,Australia
1,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,2,2.0,NaN,NaN,NaN,0 days 00:00:02.974000,Finished,18.0,58.0,Australia
2,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,3,4.0,NaN,NaN,NaN,0 days 00:00:15.519000,Finished,15.0,58.0,Australia
3,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4,7.0,NaN,NaN,NaN,0 days 00:00:16.144000,Finished,12.0,58.0,Australia
4,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,5,6.0,NaN,NaN,NaN,0 days 00:00:51.741000,Finished,10.0,58.0,Australia

## 📊 Interpretation

### 🇬🇧 English

The dataset inspection provides an overview of the dataset size, column structure, and available data. This initial inspection helps identify potential issues before the cleaning process begins.

---

### 🇮🇩 Bahasa Indonesia

Pemeriksaan dataset memberikan gambaran mengenai ukuran dataset, struktur kolom, dan data yang tersedia. Pemeriksaan awal ini membantu mengidentifikasi potensi masalah sebelum proses data cleaning dilakukan.

# Step 4: Check Data Types

## 🎯 Objective

Verify that each column has the appropriate data type for analysis.

---

## 🇬🇧 English

### Purpose

Checking data types ensures that numerical columns are stored as numeric values, text columns as strings, and date/time columns in the correct format. Proper data types are essential for accurate analysis and modeling.

### Expected Output

A summary of all column data types is displayed, allowing us to identify any incorrect data types that require conversion.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Memastikan setiap kolom memiliki tipe data yang sesuai untuk proses analisis. Kolom numerik harus bertipe numerik, kolom teks bertipe string, dan kolom tanggal bertipe datetime.

### Output yang Diharapkan

Daftar tipe data setiap kolom berhasil ditampilkan sehingga dapat diketahui apakah ada tipe data yang perlu diperbaiki.

In [103]:
# Display data types

wdc.dtypes

DriverNumber            int64
BroadcastName          object
Abbreviation           object
DriverId               object
TeamName               object
TeamColor              object
TeamId                 object
FirstName              object
LastName               object
FullName               object
HeadshotUrl            object
CountryCode           float64
Position              float64
ClassifiedPosition     object
GridPosition          float64
Q1                    float64
Q2                    float64
Q3                    float64
Time                   object
Status                 object
Points                float64
Laps                  float64
GrandPrix              object
dtype: object

## 📊 Interpretation

### 🇬🇧 English

The data types of all columns have been displayed successfully. This step helps identify whether each variable is stored in an appropriate format for analysis. If any incorrect data types are found, they will be converted during the cleaning process.

---

### 🇮🇩 Bahasa Indonesia

Tipe data seluruh kolom berhasil ditampilkan. Langkah ini membantu memastikan bahwa setiap variabel telah disimpan dalam format yang sesuai untuk analisis. Jika ditemukan tipe data yang kurang tepat, maka akan diperbaiki pada proses data cleaning.

# Step 5: Check Missing Values

## 🎯 Objective

Identify missing values in the dataset before performing data cleaning.

---

## 🇬🇧 English

### Purpose

Missing values may affect statistical analysis, visualization, and predictive modeling. This step identifies which columns contain missing data.

### Expected Output

A summary showing the number of missing values in each column.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Mengidentifikasi nilai yang hilang (missing values) pada dataset sebelum dilakukan proses pembersihan data.

### Output yang Diharapkan

Jumlah missing values pada setiap kolom berhasil ditampilkan.

In [104]:
# Check missing values

missing_values = wdc.isnull().sum()

missing_values

DriverNumber            0
BroadcastName           0
Abbreviation            0
DriverId                0
TeamName                0
TeamColor               0
TeamId                  0
FirstName               0
LastName                0
FullName                0
HeadshotUrl             1
CountryCode           242
Position                0
ClassifiedPosition      0
GridPosition            0
Q1                    242
Q2                    242
Q3                    242
Time                   51
Status                  0
Points                  0
Laps                    0
GrandPrix               0
dtype: int64

## 📊 Interpretation

### 🇬🇧 English

The missing value summary shows the number of empty values in each column. Columns with missing values will be evaluated to determine whether they should be filled, corrected, or retained depending on their relevance to the project.

---

### 🇮🇩 Bahasa Indonesia

Ringkasan missing values menunjukkan jumlah data kosong pada setiap kolom. Kolom yang memiliki missing values akan dievaluasi untuk menentukan apakah perlu diisi, diperbaiki, atau tetap dipertahankan sesuai kebutuhan analisis.

# Step 6: Check Duplicate Records

## 🎯 Objective

Identify duplicate rows within the dataset.

---

## 🇬🇧 English

### Purpose

Duplicate records can lead to biased statistics and inaccurate analysis. This step checks whether duplicate rows exist in the dataset.

### Expected Output

The total number of duplicate rows is displayed.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Memeriksa apakah terdapat baris data yang duplikat pada dataset.

### Output yang Diharapkan

Jumlah data duplikat berhasil ditampilkan.

In [105]:
duplicates = wdc.duplicated().sum()

print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 0

## 📊 Interpretation

### 🇬🇧 English

The duplicate check identifies whether identical rows exist in the dataset. A value of zero indicates that each record is unique and no duplicate removal is required.

---

### 🇮🇩 Bahasa Indonesia

Pemeriksaan duplikasi dilakukan untuk memastikan tidak ada baris data yang identik. Jika hasilnya nol, berarti setiap data bersifat unik sehingga tidak diperlukan penghapusan data duplikat.

# Step 7: Remove Unnecessary Columns

## 🎯 Objective

Remove columns that are not relevant to the WDC prediction project.

---

## 🇬🇧 English

### Purpose

Some columns contain information that is not required for championship prediction or dashboard visualization. Removing unnecessary columns simplifies the dataset and improves analysis efficiency.

### Expected Output

A cleaner dataset containing only relevant variables for analysis and prediction.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Menghapus kolom-kolom yang tidak diperlukan dalam analisis dan prediksi World Drivers' Championship (WDC).

### Output yang Diharapkan

Dataset menjadi lebih ringkas dan hanya berisi variabel yang relevan.

In [106]:
# Columns that are not required for analysis and prediction
columns_to_drop = [
    "BroadcastName",
    "Abbreviation",
    "DriverId",
    "TeamId",
    "TeamColor",
    "HeadshotUrl",
    "CountryCode",
    "Q1",
    "Q2",
    "Q3",
    "Time",
    "FirstName",
    "LastName",
    "ClassifiedPosition",
]

wdc_clean = wdc.drop(
    columns=columns_to_drop,
    errors="ignore"
)

print("✅ Unnecessary columns removed successfully!")
print(f"Original dataset shape : {wdc.shape}")
print(f"Clean dataset shape    : {wdc_clean.shape}")

wdc_clean.head()

✅ Unnecessary columns removed successfully!
Original dataset shape : (242, 23)
Clean dataset shape    : (242, 9)

,DriverNumber,TeamName,FullName,Position,GridPosition,Status,Points,Laps,GrandPrix
0,63,Mercedes,George Russell,1.0,1.0,Finished,25.0,58.0,Australia
1,12,Mercedes,Kimi Antonelli,2.0,2.0,Finished,18.0,58.0,Australia
2,16,Ferrari,Charles Leclerc,3.0,4.0,Finished,15.0,58.0,Australia
3,44,Ferrari,Lewis Hamilton,4.0,7.0,Finished,12.0,58.0,Australia
4,1,McLaren,Lando Norris,5.0,6.0,Finished,10.0,58.0,Australia

## 📊 Interpretation

### 🇬🇧 English

Irrelevant columns have been successfully removed from the dataset. The remaining variables are sufficient for exploratory analysis, dashboard development, and WDC prediction.

---

### 🇮🇩 Bahasa Indonesia

Kolom-kolom yang tidak relevan telah berhasil dihapus dari dataset. Variabel yang tersisa sudah cukup untuk proses eksplorasi data, pembuatan dashboard, dan prediksi WDC.

# Step 8: Validate the Clean Dataset

## 🎯 Objective

Verify that the cleaned dataset is complete, consistent, and ready for analysis.

---

## 🇬🇧 English

### Purpose

After removing unnecessary columns, it is important to verify the final dataset structure before exporting it.

### Expected Output

The cleaned dataset displays the expected number of columns and correct data types.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Memastikan dataset hasil cleaning sudah benar sebelum disimpan.

### Output yang Diharapkan

Dataset memiliki struktur kolom yang sesuai dan siap digunakan untuk analisis.

In [107]:
wdc_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DriverNumber  242 non-null    int64
 1   TeamName      242 non-null    object
 2   FullName      242 non-null    object
 3   Position      242 non-null    float64
 4   GridPosition  242 non-null    float64
 5   Status        242 non-null    object
 6   Points        242 non-null    float64
 7   Laps          242 non-null    float64
 8   GrandPrix     242 non-null    object
dtypes: float64(4), int64(1), object(4)
memory usage: 17.1+ KB

In [108]:
wdc_clean.head()

,DriverNumber,TeamName,FullName,Position,GridPosition,Status,Points,Laps,GrandPrix
0,63,Mercedes,George Russell,1.0,1.0,Finished,25.0,58.0,Australia
1,12,Mercedes,Kimi Antonelli,2.0,2.0,Finished,18.0,58.0,Australia
2,16,Ferrari,Charles Leclerc,3.0,4.0,Finished,15.0,58.0,Australia
3,44,Ferrari,Lewis Hamilton,4.0,7.0,Finished,12.0,58.0,Australia
4,1,McLaren,Lando Norris,5.0,6.0,Finished,10.0,58.0,Australia

In [109]:
wdc_clean.shape

(242, 9)

In [110]:
# Check completed races in the cleaned dataset

completed_races = wdc_clean["GrandPrix"].dropna().unique()

print("Completed Grands Prix:")
for i, race in enumerate(completed_races, start=1):
    print(f"{i}. {race}")

print(f"\nTotal completed races in dataset: {len(completed_races)}")

Completed Grands Prix:
1. Australia
2. China
3. Japan
4. Miami
5. Canada
6. Monaco
7. Austria
8. Great Britain
9. Belgium
10. Hungary
11. Netherlands

Total completed races in dataset: 11

## 📊 Interpretation

### 🇬🇧 English

The cleaned dataset has been validated successfully. Only relevant variables remain, making the dataset suitable for exploratory analysis, visualization, and predictive modeling.

---

### 🇮🇩 Bahasa Indonesia

Dataset hasil cleaning telah berhasil divalidasi. Dataset kini hanya berisi variabel yang relevan sehingga siap digunakan untuk eksplorasi data, visualisasi, dan pemodelan prediksi.

# Step 9: Export Clean Dataset

## 🎯 Objective

Save the cleaned dataset for future analysis.

---

## 🇬🇧 English

### Purpose

Export the cleaned dataset into the processed data folder.

### Expected Output

A CSV file containing the cleaned dataset.

---

## 🇮🇩 Bahasa Indonesia

### Tujuan

Menyimpan dataset hasil cleaning ke dalam folder processed.

### Output yang Diharapkan

File CSV berhasil tersimpan.

In [111]:
processed_path = Path("../data/processed")

processed_path.mkdir(
    parents=True,
    exist_ok=True
)

wdc_clean.to_csv(
    processed_path / "wdc_clean.csv",
    index=False
)

print("✅ Clean dataset exported successfully!")

✅ Clean dataset exported successfully!

## 📊 Interpretation

### 🇬🇧 English

The cleaned dataset has been successfully exported and is now ready for exploratory data analysis and dashboard development.

---

### 🇮🇩 Bahasa Indonesia

Dataset hasil cleaning berhasil disimpan dan siap digunakan pada tahap Exploratory Data Analysis (EDA) serta pembuatan dashboard.

# Step 10: Cleaning Summary

## 📊 Summary

### 🇬🇧 English

The data cleaning process has been completed successfully.

Cleaning activities performed:

- Loaded the master dataset
- Checked dataset structure
- Verified data types
- Identified missing values
- Checked duplicate records
- Removed unnecessary columns
- Validated the cleaned dataset
- Exported the final dataset

The cleaned dataset is now ready for Exploratory Data Analysis (EDA).

---

### 🇮🇩 Bahasa Indonesia

Proses data cleaning telah selesai dilakukan.

Tahapan yang dilakukan:

- Memuat dataset utama
- Memeriksa struktur dataset
- Memeriksa tipe data
- Mengidentifikasi missing values
- Memeriksa data duplikat
- Menghapus kolom yang tidak diperlukan
- Memvalidasi dataset hasil cleaning
- Menyimpan dataset bersih

Dataset kini siap digunakan untuk Exploratory Data Analysis (EDA).